//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_5_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class titles
    {
        public int title_id { get; set; }
        public int pub_id { get; set; }
        public string title { get; set; }
    
        public virtual publishers publishers { get; set; }
    }
}
